//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Allowance.
        /// </summary>
        internal static string AddAllowance {
            get {
                return ResourceManager.GetString("AddAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Country.
        /// </summary>
        internal static string AddCountry {
            get {
                return ResourceManager.GetString("AddCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Deduction.
        /// </summary>
        internal static string AddDeduction {
            get {
                return ResourceManager.GetString("AddDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Department.
        /// </summary>
        internal static string AddDepartment {
            get {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Designation.
        /// </summary>
        internal static string AddDesignation {
            get {
                return ResourceManager.GetString("AddDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Education.
        /// </summary>
        internal static string AddEducation {
            get {
                return ResourceManager.GetString("AddEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        internal static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee Grade.
        /// </summary>
        internal static string AddEmployeeGrade {
            get {
                return ResourceManager.GetString("AddEmployeeGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee Loan.
        /// </summary>
        internal static string AddEmployeeLoan {
            get {
                return ResourceManager.GetString("AddEmployeeLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee Salary.
        /// </summary>
        internal static string AddEmployeeSalary {
            get {
                return ResourceManager.GetString("AddEmployeeSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee Type.
        /// </summary>
        internal static string AddEmployeeType {
            get {
                return ResourceManager.GetString("AddEmployeeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Financial Year.
        /// </summary>
        internal static string AddFinancialYear {
            get {
                return ResourceManager.GetString("AddFinancialYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Holiday.
        /// </summary>
        internal static string AddHoliday {
            get {
                return ResourceManager.GetString("AddHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Leave Category.
        /// </summary>
        internal static string AddLeaveCategory {
            get {
                return ResourceManager.GetString("AddLeaveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shift.
        /// </summary>
        internal static string AddShift {
            get {
                return ResourceManager.GetString("AddShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add State.
        /// </summary>
        internal static string AddState {
            get {
                return ResourceManager.GetString("AddState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance.
        /// </summary>
        internal static string Allowance {
            get {
                return ResourceManager.GetString("Allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (This allowance value will be use Leave or OT Calculation).
        /// </summary>
        internal static string AllowanceConsiderNote {
            get {
                return ResourceManager.GetString("AllowanceConsiderNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Leave.
        /// </summary>
        internal static string AllowedLeave {
            get {
                return ResourceManager.GetString("AllowedLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} name already exist, please add another name..
        /// </summary>
        internal static string AlreadyExistMsg {
            get {
                return ResourceManager.GetString("AlreadyExistMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Date.
        /// </summary>
        internal static string ApplyDate {
            get {
                return ResourceManager.GetString("ApplyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Leave Application.
        /// </summary>
        internal static string ApplyLeaveApplication {
            get {
                return ResourceManager.GetString("ApplyLeaveApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        internal static string ApprovedBy {
            get {
                return ResourceManager.GetString("ApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        internal static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Chart.
        /// </summary>
        internal static string AttendanceChart {
            get {
                return ResourceManager.GetString("AttendanceChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Entry.
        /// </summary>
        internal static string AttendanceEntry {
            get {
                return ResourceManager.GetString("AttendanceEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Information.
        /// </summary>
        internal static string AttendanceInformation {
            get {
                return ResourceManager.GetString("AttendanceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Report.
        /// </summary>
        internal static string AttendanceReport {
            get {
                return ResourceManager.GetString("AttendanceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendances.
        /// </summary>
        internal static string Attendances {
            get {
                return ResourceManager.GetString("Attendances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct username and password..
        /// </summary>
        internal static string AuthenticationFailMsg {
            get {
                return ResourceManager.GetString("AuthenticationFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Information.
        /// </summary>
        internal static string BankInformation {
            get {
                return ResourceManager.GetString("BankInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic (36%).
        /// </summary>
        internal static string Basic36 {
            get {
                return ResourceManager.GetString("Basic36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        internal static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Leave.
        /// </summary>
        internal static string CalculateLeave {
            get {
                return ResourceManager.GetString("CalculateLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calender.
        /// </summary>
        internal static string Calender {
            get {
                return ResourceManager.GetString("Calender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast.
        /// </summary>
        internal static string Cast {
            get {
                return ResourceManager.GetString("Cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        internal static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Details.
        /// </summary>
        internal static string CompanyDetails {
            get {
                return ResourceManager.GetString("CompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider Half Leave.
        /// </summary>
        internal static string ConsiderHalfLeave {
            get {
                return ResourceManager.GetString("ConsiderHalfLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details.
        /// </summary>
        internal static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Paper.
        /// </summary>
        internal static string ContractPaper {
            get {
                return ResourceManager.GetString("ContractPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        internal static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name.
        /// </summary>
        internal static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string DateofBirth {
            get {
                return ResourceManager.GetString("DateofBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        internal static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction.
        /// </summary>
        internal static string Deduction {
            get {
                return ResourceManager.GetString("Deduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (This deduction value will be use Leave or OT Calculation).
        /// </summary>
        internal static string DeductionConsiderNote {
            get {
                return ResourceManager.GetString("DeductionConsiderNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been deleted successfully..
        /// </summary>
        internal static string DeletionSuccessMsg {
            get {
                return ResourceManager.GetString("DeletionSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        internal static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Attendance.
        /// </summary>
        internal static string DeviceAttendance {
            get {
                return ResourceManager.GetString("DeviceAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divorced.
        /// </summary>
        internal static string Divorced {
            get {
                return ResourceManager.GetString("Divorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        internal static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Attendance.
        /// </summary>
        internal static string EmployeeAttendance {
            get {
                return ResourceManager.GetString("EmployeeAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Attendance Entry.
        /// </summary>
        internal static string EmployeeAttendanceEntry {
            get {
                return ResourceManager.GetString("EmployeeAttendanceEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Detail.
        /// </summary>
        internal static string EmployeeDetail {
            get {
                return ResourceManager.GetString("EmployeeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Detail Report.
        /// </summary>
        internal static string EmployeeDetailReport {
            get {
                return ResourceManager.GetString("EmployeeDetailReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Documents.
        /// </summary>
        internal static string EmployeeDocuments {
            get {
                return ResourceManager.GetString("EmployeeDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Email.
        /// </summary>
        internal static string EmployeeEmail {
            get {
                return ResourceManager.GetString("EmployeeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Grade.
        /// </summary>
        internal static string EmployeeGrade {
            get {
                return ResourceManager.GetString("EmployeeGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Leave.
        /// </summary>
        internal static string EmployeeLeave {
            get {
                return ResourceManager.GetString("EmployeeLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Loan.
        /// </summary>
        internal static string EmployeeLoan {
            get {
                return ResourceManager.GetString("EmployeeLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        internal static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee No.
        /// </summary>
        internal static string EmployeeNo {
            get {
                return ResourceManager.GetString("EmployeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Paid Salary.
        /// </summary>
        internal static string EmployeePaidSalary {
            get {
                return ResourceManager.GetString("EmployeePaidSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Resign.
        /// </summary>
        internal static string EmployeeResign {
            get {
                return ResourceManager.GetString("EmployeeResign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Salary.
        /// </summary>
        internal static string EmployeeSalary {
            get {
                return ResourceManager.GetString("EmployeeSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Salary Process.
        /// </summary>
        internal static string EmployeeSalaryProcess {
            get {
                return ResourceManager.GetString("EmployeeSalaryProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Salary Slip.
        /// </summary>
        internal static string EmployeeSalarySlip {
            get {
                return ResourceManager.GetString("EmployeeSalarySlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Shift.
        /// </summary>
        internal static string EmployeeShift {
            get {
                return ResourceManager.GetString("EmployeeShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Type.
        /// </summary>
        internal static string EmployeeType {
            get {
                return ResourceManager.GetString("EmployeeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp. No.
        /// </summary>
        internal static string EmpNo {
            get {
                return ResourceManager.GetString("EmpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date Half Leave.
        /// </summary>
        internal static string EndDateHalfLeave {
            get {
                return ResourceManager.GetString("EndDateHalfLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again or Contact to support team..
        /// </summary>
        internal static string ExceptionErrMsg {
            get {
                return ResourceManager.GetString("ExceptionErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s Name.
        /// </summary>
        internal static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax No..
        /// </summary>
        internal static string FaxNo {
            get {
                return ResourceManager.GetString("FaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeMale.
        /// </summary>
        internal static string FeMale {
            get {
                return ResourceManager.GetString("FeMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Month.
        /// </summary>
        internal static string FinancialMonth {
            get {
                return ResourceManager.GetString("FinancialMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Year.
        /// </summary>
        internal static string FinancialYear {
            get {
                return ResourceManager.GetString("FinancialYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are only one step a way from your new password, recover your password now..
        /// </summary>
        internal static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date - To Date.
        /// </summary>
        internal static string FromDateToDate {
            get {
                return ResourceManager.GetString("FromDateToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Email.
        /// </summary>
        internal static string FromEmail {
            get {
                return ResourceManager.GetString("FromEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Time.
        /// </summary>
        internal static string FromTime {
            get {
                return ResourceManager.GetString("FromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        internal static string GenerateReport {
            get {
                return ResourceManager.GetString("GenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        internal static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotline No..
        /// </summary>
        internal static string HotlineNo {
            get {
                return ResourceManager.GetString("HotlineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR &amp; PayRoll.
        /// </summary>
        internal static string HRPayRoll {
            get {
                return ResourceManager.GetString("HRPayRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Proof.
        /// </summary>
        internal static string IDProof {
            get {
                return ResourceManager.GetString("IDProof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment / Month.
        /// </summary>
        internal static string InstallmentMonth {
            get {
                return ResourceManager.GetString("InstallmentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview.
        /// </summary>
        internal static string Interview {
            get {
                return ResourceManager.GetString("Interview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Time.
        /// </summary>
        internal static string InTime {
            get {
                return ResourceManager.GetString("InTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Approve.
        /// </summary>
        internal static string IsApprove {
            get {
                return ResourceManager.GetString("IsApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsConsider.
        /// </summary>
        internal static string IsConsider {
            get {
                return ResourceManager.GetString("IsConsider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Enable SSL.
        /// </summary>
        internal static string IsEnableSSL {
            get {
                return ResourceManager.GetString("IsEnableSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Paid.
        /// </summary>
        internal static string IsPaid {
            get {
                return ResourceManager.GetString("IsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Date.
        /// </summary>
        internal static string JoinDate {
            get {
                return ResourceManager.GetString("JoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining Letter.
        /// </summary>
        internal static string JoiningLetter {
            get {
                return ResourceManager.GetString("JoiningLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Application.
        /// </summary>
        internal static string LeaveApplication {
            get {
                return ResourceManager.GetString("LeaveApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Category.
        /// </summary>
        internal static string LeaveCategory {
            get {
                return ResourceManager.GetString("LeaveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Date.
        /// </summary>
        internal static string LeaveDate {
            get {
                return ResourceManager.GetString("LeaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Description.
        /// </summary>
        internal static string LeaveDescription {
            get {
                return ResourceManager.GetString("LeaveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Details.
        /// </summary>
        internal static string LeaveDetails {
            get {
                return ResourceManager.GetString("LeaveDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Management.
        /// </summary>
        internal static string LeaveManagement {
            get {
                return ResourceManager.GetString("LeaveManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave / Month.
        /// </summary>
        internal static string LeaveMonth {
            get {
                return ResourceManager.GetString("LeaveMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Opening Details.
        /// </summary>
        internal static string LeaveOpeningDetails {
            get {
                return ResourceManager.GetString("LeaveOpeningDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Report.
        /// </summary>
        internal static string LeaveReport {
            get {
                return ResourceManager.GetString("LeaveReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves.
        /// </summary>
        internal static string Leaves {
            get {
                return ResourceManager.GetString("Leaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Salary.
        /// </summary>
        internal static string LeaveSalary {
            get {
                return ResourceManager.GetString("LeaveSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan.
        /// </summary>
        internal static string Loan {
            get {
                return ResourceManager.GetString("Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Date.
        /// </summary>
        internal static string LoanDate {
            get {
                return ResourceManager.GetString("LoanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Detail.
        /// </summary>
        internal static string LoanDetail {
            get {
                return ResourceManager.GetString("LoanDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Management.
        /// </summary>
        internal static string LoanManagement {
            get {
                return ResourceManager.GetString("LoanManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Report.
        /// </summary>
        internal static string LoanReport {
            get {
                return ResourceManager.GetString("LoanReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In to your Account.
        /// </summary>
        internal static string LogIntoyourAccount {
            get {
                return ResourceManager.GetString("LogIntoyourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string Log_In {
            get {
                return ResourceManager.GetString("Log_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maratial Status.
        /// </summary>
        internal static string MaratialStatus {
            get {
                return ResourceManager.GetString("MaratialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        internal static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masters.
        /// </summary>
        internal static string Masters {
            get {
                return ResourceManager.GetString("Masters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        internal static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        internal static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Salary.
        /// </summary>
        internal static string NetSalary {
            get {
                return ResourceManager.GetString("NetSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No any find out attendnace entry. Please enter attendance entry..
        /// </summary>
        internal static string NoAnyAttendanceMsg {
            get {
                return ResourceManager.GetString("NoAnyAttendanceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Person.
        /// </summary>
        internal static string NoOfPerson {
            get {
                return ResourceManager.GetString("NoOfPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found..
        /// </summary>
        internal static string NoRecordFoundMsg {
            get {
                return ResourceManager.GetString("NoRecordFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Letter.
        /// </summary>
        internal static string OfferLetter {
            get {
                return ResourceManager.GetString("OfferLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official Details.
        /// </summary>
        internal static string OfficialDetails {
            get {
                return ResourceManager.GetString("OfficialDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your old password do not match current password. Please enter correct password..
        /// </summary>
        internal static string OldPasswordNotMatchMsg {
            get {
                return ResourceManager.GetString("OldPasswordNotMatchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Hand Salary.
        /// </summary>
        internal static string OnHandSalary {
            get {
                return ResourceManager.GetString("OnHandSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Document.
        /// </summary>
        internal static string OtherDocument {
            get {
                return ResourceManager.GetString("OtherDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Time.
        /// </summary>
        internal static string OutTime {
            get {
                return ResourceManager.GetString("OutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Time.
        /// </summary>
        internal static string OverTime {
            get {
                return ResourceManager.GetString("OverTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime Hours.
        /// </summary>
        internal static string OvertimeHours {
            get {
                return ResourceManager.GetString("OvertimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Time Report.
        /// </summary>
        internal static string OverTimeReport {
            get {
                return ResourceManager.GetString("OverTimeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Time Salary.
        /// </summary>
        internal static string OverTimeSalary {
            get {
                return ResourceManager.GetString("OverTimeSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Allowance.
        /// </summary>
        internal static string PaidAllowance {
            get {
                return ResourceManager.GetString("PaidAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Basic.
        /// </summary>
        internal static string PaidBasic {
            get {
                return ResourceManager.GetString("PaidBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Date.
        /// </summary>
        internal static string PaidDate {
            get {
                return ResourceManager.GetString("PaidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Deduction.
        /// </summary>
        internal static string PaidDeduction {
            get {
                return ResourceManager.GetString("PaidDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Details.
        /// </summary>
        internal static string PersonalDetails {
            get {
                return ResourceManager.GetString("PersonalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PF Number.
        /// </summary>
        internal static string PFNumber {
            get {
                return ResourceManager.GetString("PFNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code.
        /// </summary>
        internal static string PinCode {
            get {
                return ResourceManager.GetString("PinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        internal static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present Days.
        /// </summary>
        internal static string PresentDays {
            get {
                return ResourceManager.GetString("PresentDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Tax.
        /// </summary>
        internal static string ProfessionalTax {
            get {
                return ResourceManager.GetString("ProfessionalTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        internal static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive / Approve Email Ids.
        /// </summary>
        internal static string ReceiveApproveEmailIds {
            get {
                return ResourceManager.GetString("ReceiveApproveEmailIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:Receive / Approve Email Ids set multiple then add comma separate i.e. hr1@gmail.com,admin@gmail.com.
        /// </summary>
        internal static string ReceiveEmailNote {
            get {
                return ResourceManager.GetString("ReceiveEmailNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reference used in another place, you cannot perform delete action..
        /// </summary>
        internal static string ReferenceExistMsg {
            get {
                return ResourceManager.GetString("ReferenceExistMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation.
        /// </summary>
        internal static string Relation {
            get {
                return ResourceManager.GetString("Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Leave.
        /// </summary>
        internal static string RemainingLeave {
            get {
                return ResourceManager.GetString("RemainingLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply Employee Leave.
        /// </summary>
        internal static string ReplyEmployeeLeave {
            get {
                return ResourceManager.GetString("ReplyEmployeeLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset successfully..
        /// </summary>
        internal static string ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are only one step a way from your new password, recover your password now..
        /// </summary>
        internal static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resign.
        /// </summary>
        internal static string Resign {
            get {
                return ResourceManager.GetString("Resign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resignation Information.
        /// </summary>
        internal static string ResignationInformation {
            get {
                return ResourceManager.GetString("ResignationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resign Date.
        /// </summary>
        internal static string ResignDate {
            get {
                return ResourceManager.GetString("ResignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resign Letter.
        /// </summary>
        internal static string ResignLetter {
            get {
                return ResourceManager.GetString("ResignLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Chart.
        /// </summary>
        internal static string SalaryChart {
            get {
                return ResourceManager.GetString("SalaryChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Management.
        /// </summary>
        internal static string SalaryManagement {
            get {
                return ResourceManager.GetString("SalaryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Report.
        /// </summary>
        internal static string SalaryReport {
            get {
                return ResourceManager.GetString("SalaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Slip.
        /// </summary>
        internal static string SalarySlip {
            get {
                return ResourceManager.GetString("SalarySlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Allowance.
        /// </summary>
        internal static string SaveAllowance {
            get {
                return ResourceManager.GetString("SaveAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Company.
        /// </summary>
        internal static string SaveCompany {
            get {
                return ResourceManager.GetString("SaveCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Country.
        /// </summary>
        internal static string SaveCountry {
            get {
                return ResourceManager.GetString("SaveCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Deduction.
        /// </summary>
        internal static string SaveDeduction {
            get {
                return ResourceManager.GetString("SaveDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Department.
        /// </summary>
        internal static string SaveDepartment {
            get {
                return ResourceManager.GetString("SaveDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Designation.
        /// </summary>
        internal static string SaveDesignation {
            get {
                return ResourceManager.GetString("SaveDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Education.
        /// </summary>
        internal static string SaveEducation {
            get {
                return ResourceManager.GetString("SaveEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Employee.
        /// </summary>
        internal static string SaveEmployee {
            get {
                return ResourceManager.GetString("SaveEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Employee Grade.
        /// </summary>
        internal static string SaveEmployeeGrade {
            get {
                return ResourceManager.GetString("SaveEmployeeGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Employee Loan.
        /// </summary>
        internal static string SaveEmployeeLoan {
            get {
                return ResourceManager.GetString("SaveEmployeeLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Employee Resign.
        /// </summary>
        internal static string SaveEmployeeResign {
            get {
                return ResourceManager.GetString("SaveEmployeeResign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Employee Salary.
        /// </summary>
        internal static string SaveEmployeeSalary {
            get {
                return ResourceManager.GetString("SaveEmployeeSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Employee Salary Process.
        /// </summary>
        internal static string SaveEmployeeSalaryProcess {
            get {
                return ResourceManager.GetString("SaveEmployeeSalaryProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Employee Type.
        /// </summary>
        internal static string SaveEmployeeType {
            get {
                return ResourceManager.GetString("SaveEmployeeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Financial Year.
        /// </summary>
        internal static string SaveFinancialYear {
            get {
                return ResourceManager.GetString("SaveFinancialYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Holiday.
        /// </summary>
        internal static string SaveHoliday {
            get {
                return ResourceManager.GetString("SaveHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Leave Category.
        /// </summary>
        internal static string SaveLeaveCategory {
            get {
                return ResourceManager.GetString("SaveLeaveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Shift.
        /// </summary>
        internal static string SaveShift {
            get {
                return ResourceManager.GetString("SaveShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save State.
        /// </summary>
        internal static string SaveState {
            get {
                return ResourceManager.GetString("SaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been saved successfully..
        /// </summary>
        internal static string SaveSuccessMsg {
            get {
                return ResourceManager.GetString("SaveSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Visitor.
        /// </summary>
        internal static string SaveVisitor {
            get {
                return ResourceManager.GetString("SaveVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select --.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Year --.
        /// </summary>
        internal static string SelectYear {
            get {
                return ResourceManager.GetString("SelectYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email Settings.
        /// </summary>
        internal static string SendEmailSettings {
            get {
                return ResourceManager.GetString("SendEmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send the e-mail because your network problem. Please try again!.
        /// </summary>
        internal static string SendFailMsg {
            get {
                return ResourceManager.GetString("SendFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Link.
        /// </summary>
        internal static string SendLink {
            get {
                return ResourceManager.GetString("SendLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great. We have sent reset password link in your email..
        /// </summary>
        internal static string SendLinkSuccessMsg {
            get {
                return ResourceManager.GetString("SendLinkSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Management.
        /// </summary>
        internal static string ShiftManagement {
            get {
                return ResourceManager.GetString("ShiftManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Host.
        /// </summary>
        internal static string SMTPHost {
            get {
                return ResourceManager.GetString("SMTPHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Port.
        /// </summary>
        internal static string SMTPPort {
            get {
                return ResourceManager.GetString("SMTPPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date - End Date.
        /// </summary>
        internal static string StartDateEndDate {
            get {
                return ResourceManager.GetString("StartDateEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date Half Leave.
        /// </summary>
        internal static string StartDateHalfLeave {
            get {
                return ResourceManager.GetString("StartDateHalfLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Name.
        /// </summary>
        internal static string StateName {
            get {
                return ResourceManager.GetString("StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Allowance.
        /// </summary>
        internal static string TotalAllowance {
            get {
                return ResourceManager.GetString("TotalAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Current Employee.
        /// </summary>
        internal static string TotalCurrentEmployee {
            get {
                return ResourceManager.GetString("TotalCurrentEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Days.
        /// </summary>
        internal static string TotalDays {
            get {
                return ResourceManager.GetString("TotalDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Deduction.
        /// </summary>
        internal static string TotalDeduction {
            get {
                return ResourceManager.GetString("TotalDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Employee.
        /// </summary>
        internal static string TotalEmployee {
            get {
                return ResourceManager.GetString("TotalEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Holiday.
        /// </summary>
        internal static string TotalHoliday {
            get {
                return ResourceManager.GetString("TotalHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Holidays.
        /// </summary>
        internal static string TotalHolidays {
            get {
                return ResourceManager.GetString("TotalHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Leave.
        /// </summary>
        internal static string TotalLeave {
            get {
                return ResourceManager.GetString("TotalLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Loan Amount.
        /// </summary>
        internal static string TotalLoanAmount {
            get {
                return ResourceManager.GetString("TotalLoanAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Months.
        /// </summary>
        internal static string TotalMonths {
            get {
                return ResourceManager.GetString("TotalMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Over Time Days.
        /// </summary>
        internal static string TotalOverTimeDays {
            get {
                return ResourceManager.GetString("TotalOverTimeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Overtime Hours.
        /// </summary>
        internal static string TotalOvertimeHours {
            get {
                return ResourceManager.GetString("TotalOvertimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Paid.
        /// </summary>
        internal static string TotalPaid {
            get {
                return ResourceManager.GetString("TotalPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Paid Allowance.
        /// </summary>
        internal static string TotalPaidAllowance {
            get {
                return ResourceManager.GetString("TotalPaidAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Paid Deduction.
        /// </summary>
        internal static string TotalPaidDeduction {
            get {
                return ResourceManager.GetString("TotalPaidDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Present.
        /// </summary>
        internal static string TotalPresent {
            get {
                return ResourceManager.GetString("TotalPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Present Days.
        /// </summary>
        internal static string TotalPresentDays {
            get {
                return ResourceManager.GetString("TotalPresentDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Resign Employee.
        /// </summary>
        internal static string TotalResignEmployee {
            get {
                return ResourceManager.GetString("TotalResignEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Salary.
        /// </summary>
        internal static string TotalSalary {
            get {
                return ResourceManager.GetString("TotalSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Weekly Off.
        /// </summary>
        internal static string TotalWeeklyOff {
            get {
                return ResourceManager.GetString("TotalWeeklyOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Working Hours.
        /// </summary>
        internal static string TotalWorkingHours {
            get {
                return ResourceManager.GetString("TotalWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Time.
        /// </summary>
        internal static string ToTime {
            get {
                return ResourceManager.GetString("ToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Married.
        /// </summary>
        internal static string UnMarried {
            get {
                return ResourceManager.GetString("UnMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Birthdays.
        /// </summary>
        internal static string UpcomingBirthdays {
            get {
                return ResourceManager.GetString("UpcomingBirthdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Holidays.
        /// </summary>
        internal static string UpcomingHolidays {
            get {
                return ResourceManager.GetString("UpcomingHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Employee Shift.
        /// </summary>
        internal static string UpdateEmployeeShift {
            get {
                return ResourceManager.GetString("UpdateEmployeeShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Leave.
        /// </summary>
        internal static string UsedLeave {
            get {
                return ResourceManager.GetString("UsedLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Detail.
        /// </summary>
        internal static string UserDetail {
            get {
                return ResourceManager.GetString("UserDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        internal static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email.
        /// </summary>
        internal static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email Password.
        /// </summary>
        internal static string UserEmailPassword {
            get {
                return ResourceManager.GetString("UserEmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username does not exist. Please enter correct username..
        /// </summary>
        internal static string UsernameNotExistsMsg {
            get {
                return ResourceManager.GetString("UsernameNotExistsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit In Date Time.
        /// </summary>
        internal static string VisitInDateTime {
            get {
                return ResourceManager.GetString("VisitInDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor.
        /// </summary>
        internal static string Visitor {
            get {
                return ResourceManager.GetString("Visitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Out Date Time.
        /// </summary>
        internal static string VisitOutDateTime {
            get {
                return ResourceManager.GetString("VisitOutDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Reference.
        /// </summary>
        internal static string VisitReference {
            get {
                return ResourceManager.GetString("VisitReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Name.
        /// </summary>
        internal static string VisitToName {
            get {
                return ResourceManager.GetString("VisitToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Off.
        /// </summary>
        internal static string WeeklyOff {
            get {
                return ResourceManager.GetString("WeeklyOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widowed.
        /// </summary>
        internal static string Widowed {
            get {
                return ResourceManager.GetString("Widowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Days.
        /// </summary>
        internal static string WorkingDays {
            get {
                return ResourceManager.GetString("WorkingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours.
        /// </summary>
        internal static string WorkingHours {
            get {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
