//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPEntities : DbContext
    {
        public ERPEntities()
            : base("name=ERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllowanceMaster> AllowanceMasters { get; set; }
        public virtual DbSet<CountryMaster> CountryMasters { get; set; }
        public virtual DbSet<DeductionMaster> DeductionMasters { get; set; }
        public virtual DbSet<DepartmentMaster> DepartmentMasters { get; set; }
        public virtual DbSet<DesignationMaster> DesignationMasters { get; set; }
        public virtual DbSet<EmployeeAllowanceMap> EmployeeAllowanceMaps { get; set; }
        public virtual DbSet<EmployeeAttachment> EmployeeAttachments { get; set; }
        public virtual DbSet<EmployeeAttendance> EmployeeAttendances { get; set; }
        public virtual DbSet<EmployeeDeductionMap> EmployeeDeductionMaps { get; set; }
        public virtual DbSet<EmployeeGradeMaster> EmployeeGradeMasters { get; set; }
        public virtual DbSet<EmployeeLeaveCategory> EmployeeLeaveCategories { get; set; }
        public virtual DbSet<EmployeeLoan> EmployeeLoans { get; set; }
        public virtual DbSet<EmployeeMaster> EmployeeMasters { get; set; }
        public virtual DbSet<EmployeePaidAllowanceMap> EmployeePaidAllowanceMaps { get; set; }
        public virtual DbSet<EmployeePaidDeductionMap> EmployeePaidDeductionMaps { get; set; }
        public virtual DbSet<EmployeePaidLoan> EmployeePaidLoans { get; set; }
        public virtual DbSet<EmployeePaidSalary> EmployeePaidSalaries { get; set; }
        public virtual DbSet<EmployeeSalary> EmployeeSalaries { get; set; }
        public virtual DbSet<EmployeeTypeMaster> EmployeeTypeMasters { get; set; }
        public virtual DbSet<EmployeeWorkingDay> EmployeeWorkingDays { get; set; }
        public virtual DbSet<FinancialYearMaster> FinancialYearMasters { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<HolidayMaster> HolidayMasters { get; set; }
        public virtual DbSet<LeaveCategoryMaster> LeaveCategoryMasters { get; set; }
        public virtual DbSet<ModuleMaster> ModuleMasters { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<ShiftMaster> ShiftMasters { get; set; }
        public virtual DbSet<StateMaster> StateMasters { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<UserModuleMap> UserModuleMaps { get; set; }
        public virtual DbSet<CurrencyMaster> CurrencyMasters { get; set; }
        public virtual DbSet<DeviceMaster> DeviceMasters { get; set; }
        public virtual DbSet<EmployeeAttendanceDevice> EmployeeAttendanceDevices { get; set; }
        public virtual DbSet<EmployeeDeviceMap> EmployeeDeviceMaps { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<InvoiceMaster> InvoiceMasters { get; set; }
        public virtual DbSet<CompanyMaster> CompanyMasters { get; set; }
        public virtual DbSet<EducationMaster> EducationMasters { get; set; }
        public virtual DbSet<InterviewMaster> InterviewMasters { get; set; }
        public virtual DbSet<VisitMaster> VisitMasters { get; set; }
    }
}
