//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewMaster
    {
        public System.Guid InterviewID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public System.Guid EducationId { get; set; }
        public System.Guid DepartmentId { get; set; }
        public System.Guid DesignationId { get; set; }
        public string CurrentSalary { get; set; }
        public string ExpectedSalary { get; set; }
        public string ExperienceYear { get; set; }
        public string ExperienceMonth { get; set; }
        public Nullable<bool> IsJoiningDay { get; set; }
        public string NoticePeriod { get; set; }
        public string PersonalDetail { get; set; }
        public string ResumeName { get; set; }
        public string CertificateName { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
