//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitMaster
    {
        public System.Guid VisitID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public string VisitToName { get; set; }
        public string VisitReference { get; set; }
        public string Relation { get; set; }
        public string Purpose { get; set; }
        public Nullable<System.DateTime> VisitInDateTime { get; set; }
        public Nullable<System.DateTime> VisitOutDateTime { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> NoOfPerson { get; set; }
    }
}
